services:
  shell:
    image: ghcr.io/lchumi/shell
    container_name: shell
    ports:
      - "4200:80"
    networks:
      - mfe-network

  mfe-auth:
    image: ghcr.io/lchumi/mfe-auth
    container_name: mfe-auth
    ports:
      - "4201:80"
    networks:
      - mfe-network
    depends_on:
      - shell

  mfe-contabilidad:
    image: ghcr.io/lchumi/mfe-contabilidad
    container_name: mfe-contabilidad
    ports:
      - "4202:80"
    networks:
      - mfe-network
    depends_on:
      - shell

networks:
  mfe-network:
    driver: bridge
