name: cleanup.yml

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - "shell"
          - "mfe-auth"
          - "mfe-contabilidad"
          - "mfe-dashboard"
          - "mfe-importaciones"
          - "mfe-inventario"
          - "mfe-payments"
          - "mfe-pedidos"
          - "mfe-system-administrador"

        steps:
          - name: Delete old images - ${{ matrix.package }}
            uses: actions/delete-package-versions@v4
            with:
              owner: "LChumi"
              package-name: ${{ matrix.package }}
              package-type: 'container'
              min-versions-to-kepp: 3
              delete-only-pre-releases-versions: false
              token: ${{ secrets.GHCR_PAT }}
